name: GitHub Actions Secret Example

on:
  push:
    branches: [ master ]

jobs:
  secrets-in-github-actions:
    runs-on: self-hosted

    
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.GITHUB_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.GITHUB_TOKEN}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.GITHUB_TOKEN }}
        if:  env.WHO_TO_TRUST == 'TrustNo1'
        run: echo "I know what the secret token is!"

      # A GitHub Actions if statement with a secret environment variable
      - name: Step 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          WHO_TO_TRUST: ${{ secrets.GITHUB_TOKEN }}
        if:  env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"
